export const styles = {
  root: {
    minHeight: "100vh",
    background: "#0a0a0a",
    fontFamily: "'DM Sans', sans-serif",
    color: "#e8e0d5",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    height: 64,
    background: "#111",
    borderBottom: "1px solid #222",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: { display: "flex", alignItems: "baseline", gap: 6 },
  logoIcon: { fontSize: 22 },
  logoText: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 900,
    color: "#f97316",
    letterSpacing: 4,
  },
  logoSub: { fontSize: 11, letterSpacing: 3, color: "#666", textTransform: "uppercase" },
  nav: { display: "flex", gap: 4 },
  navBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 18px",
    background: "transparent",
    border: "1px solid transparent",
    borderRadius: 8,
    color: "#888",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "all 0.2s",
  },
  navBtnActive: {
    background: "#1a1a1a",
    border: "1px solid #f97316",
    color: "#f97316",
  },
  navIcon: { fontSize: 16 },
  headerRight: { position: "relative", cursor: "pointer" },
  notifBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    background: "#f97316",
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    width: 16,
    height: 16,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  body: { display: "flex", flex: 1, overflow: "hidden" },
  sidebar: {
    width: 240,
    minHeight: "calc(100vh - 64px)",
    background: "#111",
    borderRight: "1px solid #1e1e1e",
    padding: "24px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    overflowY: "auto",
  },
  avatarWrap: { position: "relative", marginBottom: 12 },
  avatarRing: {
    width: 70,
    height: 70,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #f97316, #8b5cf6)",
    padding: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    background: "#1a1a1a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    fontWeight: 700,
    color: "#f97316",
    fontFamily: "'Playfair Display', serif",
  },
  onlineDot: {
    position: "absolute",
    bottom: 4,
    right: 4,
    width: 12,
    height: 12,
    borderRadius: "50%",
    background: "#4ade80",
    border: "2px solid #111",
  },
  custName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 17,
    fontWeight: 700,
    color: "#f0e8de",
    textAlign: "center",
  },
  custHandle: { fontSize: 12, color: "#555", marginTop: 2, marginBottom: 10 },
  tierBadge: {
    background: "linear-gradient(135deg, #78350f, #d97706)",
    color: "#fef3c7",
    fontSize: 11,
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: 20,
    marginBottom: 16,
  },
  profileStats: {
    display: "flex",
    width: "100%",
    background: "#161616",
    borderRadius: 12,
    padding: "12px 0",
    marginBottom: 16,
    border: "1px solid #222",
  },
  statBox: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center" },
  statNum: { fontSize: 16, fontWeight: 700, color: "#f97316" },
  statLabel: { fontSize: 10, color: "#555", marginTop: 2 },
  statDivider: { width: 1, background: "#222" },
  profileInfo: { width: "100%", marginBottom: 16 },
  infoRow: { display: "flex", alignItems: "center", gap: 8, padding: "7px 0", borderBottom: "1px solid #1a1a1a" },
  infoIcon: { fontSize: 13, width: 18, textAlign: "center" },
  infoVal: { fontSize: 11, color: "#888" },
  loyaltyWrap: { width: "100%", background: "#161616", borderRadius: 12, padding: 14, border: "1px solid #222" },
  loyaltyLabel: { display: "flex", justifyContent: "space-between", marginBottom: 8, fontSize: 12, color: "#888" },
  loyaltyPts: { color: "#f97316", fontWeight: 600 },
  progressTrack: { background: "#222", borderRadius: 4, height: 6, overflow: "hidden" },
  progressBar: { height: "100%", background: "linear-gradient(90deg, #f97316, #8b5cf6)", borderRadius: 4 },
  loyaltyNote: { fontSize: 10, color: "#555", marginTop: 6, textAlign: "right" },
  main: { flex: 1, display: "flex", flexDirection: "column", overflowY: "auto" },
  scrollerOuter: {
    background: "#111",
    borderBottom: "1px solid #1e1e1e",
    padding: "10px 24px",
    display: "flex",
    alignItems: "center",
    gap: 16,
    overflow: "hidden",
  },
  scrollerTag: { fontSize: 10, letterSpacing: 2, color: "#f97316", whiteSpace: "nowrap", fontWeight: 600 },
  scrollerTrack: { flex: 1, overflow: "hidden" },
  scrollerInner: {
    display: "flex",
    gap: 12,
    animation: "scrollLeft 28s linear infinite",
    width: "max-content",
  },
  dishCard: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#1a1a1a",
    borderRadius: 8,
    padding: "6px 14px",
    border: "1px solid #2a2a2a",
    whiteSpace: "nowrap",
  },
  dishEmoji: { fontSize: 20 },
  dishInfo: { display: "flex", flexDirection: "column", gap: 2 },
  dishName: { fontSize: 12, color: "#e8e0d5", fontWeight: 500 },
  dishTag: { fontSize: 9, color: "#fff", padding: "1px 6px", borderRadius: 10, fontWeight: 600, width: "fit-content" },
  tabContent: { flex: 1, padding: "24px 28px", animation: "fadeUp 0.3s ease" },
  section: {},
  sectionHeader: { marginBottom: 20 },
  sectionTitle: { fontFamily: "'Playfair Display', serif", fontSize: 22, color: "#f0e8de" },
  sectionSub: { fontSize: 12, color: "#555", marginTop: 2 },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 16 },
  card: {
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 14,
    padding: 18,
    animation: "fadeUp 0.3s ease both",
  },
  newOrderCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    border: "1px dashed #333",
    color: "#555",
    fontSize: 32,
    minHeight: 140,
  },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  orderId: { fontSize: 13, fontWeight: 600, color: "#a0a0a0" },
  statusChip: { fontSize: 12, padding: "3px 10px", borderRadius: 20, fontWeight: 600 },
  orderItems: { fontSize: 13, color: "#888", marginBottom: 12 },
  cardBottom: { display: "flex", justifyContent: "space-between", marginBottom: 12 },
  orderDate: { fontSize: 11, color: "#555" },
  orderTotal: { fontSize: 15, fontWeight: 700, color: "#f97316" },
  reorderBtn: {
    width: "100%",
    padding: "8px",
    background: "transparent",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#888",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "all 0.2s",
  },
  paymentGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 },
  creditCard: {
    background: "linear-gradient(135deg, #1a0a00 0%, #3d1500 50%, #1a0a00 100%)",
    border: "1px solid #f97316",
    borderRadius: 18,
    padding: 24,
    height: 180,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    boxShadow: "0 0 40px #f9731620",
  },
  cardChip: { fontSize: 24, color: "#f97316" },
  cardNum: { fontSize: 18, letterSpacing: 3, color: "#f0e8de", fontWeight: 600 },
  cardMeta: { display: "flex", alignItems: "flex-end", gap: 20 },
  cardMetaLabel: { fontSize: 9, color: "#888", letterSpacing: 1 },
  cardMetaVal: { fontSize: 13, color: "#e8e0d5", fontWeight: 500 },
  cardNetwork: { marginLeft: "auto", fontSize: 18, fontWeight: 900, color: "#f97316", fontStyle: "italic" },
  paymentList: { display: "flex", flexDirection: "column", gap: 10 },
  payMethod: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 12,
    padding: "12px 16px",
  },
  payMethodName: { fontSize: 13, fontWeight: 600, color: "#e8e0d5" },
  payMethodSub: { fontSize: 11, color: "#555", marginTop: 2 },
  activeIndicator: { fontSize: 11, color: "#4ade80", fontWeight: 600 },
  addPayBtn: {
    width: "100%",
    padding: "10px",
    background: "transparent",
    border: "1px dashed #333",
    borderRadius: 10,
    color: "#555",
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  txnRow: { display: "flex", alignItems: "center", gap: 14, padding: "12px 0", borderBottom: "1px solid #1a1a1a" },
  txnIcon: { fontSize: 20 },
  txnId: { fontSize: 13, fontWeight: 600, color: "#a0a0a0" },
  txnMeta: { fontSize: 11, color: "#555", marginTop: 2 },
  txnAmount: { fontSize: 15, fontWeight: 700, color: "#f97316", marginBottom: 4 },
  cartWrap: { display: "grid", gridTemplateColumns: "1fr 360px", gap: 24 },
  cartItems: { display: "flex", flexDirection: "column", gap: 12 },
  cartRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 14,
    padding: "14px 18px",
  },
  cartEmoji: { fontSize: 30, width: 44, textAlign: "center" },
  cartName: { fontSize: 14, fontWeight: 600, color: "#e8e0d5" },
  cartPrice: { fontSize: 13, color: "#f97316", marginTop: 3 },
  qtyControl: { display: "flex", alignItems: "center", gap: 12, marginLeft: "auto" },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "1px solid #333",
    background: "#1e1e1e",
    color: "#e8e0d5",
    fontSize: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'DM Sans', sans-serif",
  },
  qtyNum: { fontSize: 15, fontWeight: 700, color: "#f97316", minWidth: 20, textAlign: "center" },
  cartSummary: {
    background: "#141414",
    border: "1px solid #222",
    borderRadius: 14,
    padding: 22,
    height: "fit-content",
    position: "sticky",
    top: 80,
  },
  summaryTitle: { fontFamily: "'Playfair Display', serif", fontSize: 18, color: "#f0e8de", marginBottom: 16 },
  summaryRow: { display: "flex", justifyContent: "space-between", fontSize: 13, color: "#888", marginBottom: 10 },
  summaryDivider: { height: 1, background: "#222", margin: "12px 0" },
  summaryTotal: { fontSize: 16, fontWeight: 700, color: "#f0e8de" },
  promoWrap: { display: "flex", gap: 8, marginTop: 14, marginBottom: 14 },
  promoInput: {
    flex: 1,
    background: "#0d0d0d",
    border: "1px solid #2a2a2a",
    borderRadius: 8,
    padding: "8px 12px",
    color: "#e8e0d5",
    fontSize: 12,
    fontFamily: "'DM Sans', sans-serif",
    outline: "none",
  },
  promoBtn: {
    background: "#1e1e1e",
    border: "1px solid #333",
    borderRadius: 8,
    color: "#888",
    fontSize: 12,
    padding: "8px 12px",
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  checkoutBtn: {
    width: "100%",
    padding: "13px",
    background: "linear-gradient(135deg, #f97316, #ea580c)",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    boxShadow: "0 4px 20px #f9731640",
  },
  profileGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 },
  formTitle: { fontFamily: "'Playfair Display', serif", fontSize: 17, color: "#f0e8de", marginBottom: 16 },
  formField: { marginBottom: 14 },
  formLabel: {
    display: "block",
    fontSize: 11,
    color: "#555",
    marginBottom: 4,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  formInput: {
    width: "100%",
    background: "#0d0d0d",
    border: "1px solid #2a2a2a",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#e8e0d5",
    fontSize: 13,
    fontFamily: "'DM Sans', sans-serif",
    outline: "none",
  },
  saveBtn: {
    marginTop: 8,
    padding: "10px 24px",
    background: "linear-gradient(135deg, #f97316, #ea580c)",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  addressCard: {
    background: "#0d0d0d",
    border: "1px solid #222",
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    position: "relative",
  },
  addrTag: {
    fontSize: 10,
    fontWeight: 700,
    background: "#f97316",
    color: "#fff",
    padding: "2px 8px",
    borderRadius: 10,
    letterSpacing: 1,
  },
  addrText: { fontSize: 12, color: "#888", marginTop: 6, marginBottom: 6 },
  editAddrBtn: {
    fontSize: 11,
    color: "#f97316",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  prefTags: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 10 },
  prefTag: {
    fontSize: 11,
    background: "#1e1e1e",
    border: "1px solid #333",
    borderRadius: 20,
    padding: "4px 12px",
    color: "#888",
  },
};

export const statusColor = {
  Delivered: { bg: "#1a3a2a", text: "#4ade80" },
  Pending: { bg: "#3a2e0a", text: "#facc15" },
  Cancelled: { bg: "#3a1a1a", text: "#f87171" },
};